# -*- coding: utf-8 -*-
"""Copy of Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzK2n4HPLB6xrJT7ZkhDKTICoX_i3EGS
"""

# 安装 Hugging Face 的 transformers 库
!pip install transformers

import pandas as pd
import torch
from transformers import DistilBertTokenizer, DistilBertModel
import os
from tqdm import tqdm

def get_text_embedding_and_save():
    # ================= 配置区域 =================
    # 输入文件路径 (建议使用处理好的 train_ready 文件)
    INPUT_CSV = 'dataset_train_ready.csv'
    # 输出文件夹
    OUTPUT_DIR = 'nlp_embeddings'
    # 模型名称 (DistilBERT 轻量且符合 Week 9 要求)
    MODEL_NAME = 'distilbert-base-uncased'
    # Token 最大长度
    MAX_LENGTH = 32
    # ===========================================

    # 1. 初始化设置
    # 强制使用 CPU，避免 GPU 版本兼容问题
    device = torch.device('cpu')
    print(f"🚀 初始化: 正使用设备 {device} 进行处理...")

    # 创建输出目录
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # 加载预训练模型和分词器
    print(f"📥 加载模型: {MODEL_NAME}...")
    try:
        tokenizer = DistilBertTokenizer.from_pretrained(MODEL_NAME)
        model = DistilBertModel.from_pretrained(MODEL_NAME).to(device)
    except Exception as e:
        print("❌ 模型加载失败，请确保已安装 transformers 并联网: ", e)
        return

    model.eval() # 切换到评估模式

    # 2. 读取数据
    print(f"📖 读取数据: {INPUT_CSV}...")
    df = pd.read_csv(INPUT_CSV)

    # 确定指令列名
    if 'final_instruction' in df.columns:
        col_name = 'final_instruction'
    elif 'instruction' in df.columns:
        col_name = 'instruction' # 注意：如果用 metadata.csv，这里可能需要解析列表
    else:
        raise ValueError("未在 CSV 中找到指令列 (final_instruction 或 instruction)")

    print(f"📊 开始处理 {len(df)} 条数据...")

    # 3. 循环处理并保存
    with torch.no_grad(): # 不计算梯度，节省内存
        for idx, row in tqdm(df.iterrows(), total=len(df), unit="img"):
            text = row[col_name]

            # 异常处理：防止空数据导致报错
            if pd.isna(text):
                text = ""
                # print(f"Warning: Row {idx} has empty instruction, using empty string.")

            # Tokenization (填充到固定长度 32)
            inputs = tokenizer(
                str(text),
                padding='max_length',
                truncation=True,
                max_length=MAX_LENGTH,
                return_tensors='pt'
            )

            # 将输入移至 CPU (其实已经在 CPU 了，但保持逻辑严谨)
            input_ids = inputs['input_ids'].to(device)
            attention_mask = inputs['attention_mask'].to(device)

            # 模型前向传播
            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            # 4. 提取语义特征
            # last_hidden_state 形状: (batch_size=1, seq_len=32, hidden_dim=768)
            # 取 [CLS] token (索引 0) 作为整句语义表示
            cls_embedding = outputs.last_hidden_state[:, 0, :] # 形状: (1, 768)

            # 压缩维度并转为 float32
            # 最终形状: (768,)
            final_tensor = cls_embedding.squeeze(0).clone().to(dtype=torch.float32)

            # 5. 保存为 .pt 文件
            # 命名格式: 行号.pt (例如 0.pt, 1.pt)
            save_path = os.path.join(OUTPUT_DIR, f"{idx}.pt")
            torch.save(final_tensor, save_path)

    print(f"✅ 处理完成！所有 Tensor 已保存至 '{OUTPUT_DIR}' 文件夹。")
    print(f"   输出格式: torch.float32")
    print(f"   输出维度: 768 (DistilBERT base)")
    print(f"   命名示例: 0.pt, 1.pt ... {len(df)-1}.pt")

if __name__ == '__main__':
    get_text_embedding_and_save()

import shutil
from google.colab import files

# 1. 将生成的文件夹打包成 zip
# 格式: shutil.make_archive(输出文件名, 'zip', 要打包的文件夹路径)
print("正在打包，请稍候...")
shutil.make_archive('nlp_embeddings_output', 'zip', 'nlp_embeddings')
print("打包完成！")

# 2. 触发浏览器下载 zip 文件
files.download('nlp_embeddings_output.zip')